# Generated by Django 2.2.10 on 2020-02-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=10)),
                ('sickname', models.CharField(max_length=10)),
                ('image', models.TextField()),
                ('symptom', models.TextField()),
                ('condition', models.TextField()),
                ('prevent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DustInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.TextField()),
                ('dataTime', models.TextField()),
                ('pm25Value', models.TextField()),
                ('pm25Value24', models.TextField()),
                ('pm10Value', models.TextField()),
                ('pm10Value24', models.TextField()),
                ('o3Value', models.TextField()),
                ('no2Value', models.TextField()),
                ('so2Value', models.TextField()),
                ('khaiValue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('created_date', models.CharField(max_length=50)),
                ('newsimg', models.TextField()),
                ('newslink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaction', models.TextField()),
                ('sky', models.TextField()),
                ('tc', models.TextField()),
                ('tmin', models.TextField()),
                ('tmx', models.TextField()),
                ('timerelease', models.TextField()),
                ('laundryday00_value', models.TextField()),
                ('laundryday00_comment', models.TextField()),
                ('laundryday01_value', models.TextField()),
                ('laundryday01_comment', models.TextField()),
                ('laundryday02_value', models.TextField()),
                ('laundryday02_comment', models.TextField()),
                ('udday00_value', models.TextField()),
                ('udday00_comment', models.TextField()),
                ('udday01_value', models.TextField()),
                ('udday01_comment', models.TextField()),
                ('udday02_value', models.TextField()),
                ('udday02_comment', models.TextField()),
                ('yesterday_name', models.TextField()),
                ('yesterday_tmax', models.TextField()),
                ('yesterday_tmin', models.TextField()),
                ('today_name', models.TextField()),
                ('today_tmax', models.TextField()),
                ('today_tmin', models.TextField()),
                ('tomorrow_name', models.TextField()),
                ('tomorrow_tmax', models.TextField()),
                ('tomorrow_tmin', models.TextField()),
                ('dayAfterTomorrow_name', models.TextField()),
                ('dayAfterTomorrow_tmax', models.TextField()),
                ('dayAfterTomorrow_tmin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherNoticeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('year', models.TextField()),
                ('month', models.TextField()),
                ('day', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
